config/routes.rb
KarnyKutas::Application.routes.draw do

  namespace :admin do
    resources :messages, only: [:index, :show, :edit, :update, :destroy]
  end

	resources :messages, only: [:index, :show, :new, :create, :search] do
		collection do
			get 'search'
		end
	end

	root 'messages#new'
end

app/models/message.rb
class Message < ActiveRecord::Base

	validates_presence_of :name, :target_name, :target_email, :body

	validates_length_of :name,        :minimum => 3
	validates_length_of :target_name, :minimum => 3
	validates_length_of :body,        :minimum => 4, :maximum => 140

	validates_format_of :target_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => 'Wrong email address'


	after_create :send_notification


	def self.search(target_email)
		find(:all, :conditions => {:target_email => target_email})
	end

	private

		def send_notification
			MessageMailer.notify_recipment(self).deliver
		end
		
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
	before_action :set_admin_message, only: [:show, :destroy]

	def index
		@admin_messages = Message.paginate(:page => params[:page], :per_page => 100)
	end

	def show
	end

	def destroy
		@admin_message.destroy
		respond_to do |format|
			format.html { redirect_to admin_messages_url }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_admin_message
			@admin_message = Message.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def admin_message_params
			params[:admin_message]
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :set_message, only: [:show]

	def search
		@messages = Message.search params[:target_email]
		redirect_to(new_message_path, notice: 'Theres no messages releated with that email address') if @messages.empty?
	end

	def index
		@messages = Message.paginate(:page => params[:page], :per_page => 20)
	end

	def show
	end

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)

		respond_to do |format|
			if @message.save
				format.html { redirect_to @message, notice: 'Message was successfully created.' }
			else
				format.html { render action: 'new' }
			end
		end
	end

	private

		# Use callbacks to share common setup or constraints between actions.
		def set_message
			@message = Message.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def message_params
			params.require(:message).permit(:name, :target_name, :target_email, :body, :ip, :status)
		end
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/admin/messages/index.html.haml
%h1 Listing admin_messages

%table
	%thead
		%tr
			%th Who?
			%th To whom?
			%th Body
			%th
			%th
			%th

	%tbody
		- @admin_messages.each do |admin_message|
			%tr
				%td= admin_message.name
				%td= admin_message.target_email
				%td= admin_message.body
				%td= link_to 'Show', admin_message
				%td= link_to 'Edit', edit_admin_message_path(admin_message)
				%td= link_to 'Destroy', admin_message, method: :delete, data: { confirm: 'Are you sure?' }

= will_paginate @admin_messages

app/views/admin/messages/show.html.haml
%p#notice= notice

= link_to 'Edit', edit_admin_message_path(@admin_message)
= link_to 'Back', admin_messages_path

app/views/layouts/application.html.haml
!!! 5
%html
	%head

		%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0"}

		%title KarnyKutas
		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags

	%body

	- flash.each do |name, msg|
		- if msg.is_a?(String)
			= content_tag :div, msg, :id => "flash_#{name}"

	= yield

app/views/messages/_form.html.haml
= simple_form_for @message do |f|

	= f.input :name
	= f.input :target_name
	= f.input :target_email
	= f.input :body

	.actions
		= f.button :submit

app/views/messages/_search_form.html.haml
= form_tag search_messages_path, :method => 'get' do |f|
  %p
    = text_field_tag :target_email, params[:target_email]
    = submit_tag "Search", :name => nil
  %p

app/views/messages/index.html.haml
%h1 Listing messages

%table
	%thead
		%tr
			%th Name
			%th Target name
			%th Target email
			%th Text

	%tbody
		- @messages.each do |message|
			%tr
				%td= message.name
				%td= message.target_name
				%td= message.target_email
				%td= message.body

%br/

= will_paginate @messages

= link_to 'New Message', new_message_path

app/views/messages/new.html.haml
%h1 New message

= render 'form'

= render 'search_form'

= link_to 'Back', messages_path

app/views/messages/search.html.haml
%h1 Listing messages

%table
	%thead
		%tr
			%th Name
			%th Target name
			%th Target email
			%th Text

	%tbody
		- @messages.each do |message|
			%tr
				%td= message.name
				%td= message.target_name
				%td= message.target_email
				%td= message.body

%br/

=# will_paginate @messages

= link_to 'New Message', new_message_path

app/views/messages/show.html.haml
%p#notice= notice

%p
  %strong
    Name:
  = @message.name

%p
  %strong
    Target name:
  = @message.target_name

%p
  %strong
    Target email:
  = @message.target_email

%p
  %strong
    Text:
  = @message.body

= link_to 'Back', messages_path